CREATE TABLE IF NOT EXISTS extractions(
    id UUID PRIMARY KEY,
    session_id UUID REFERENCES sessions(id),
    result TEXT,
    created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP
);